version = 0.1
[default.deploy.parameters]
stack_name = "ws-serverless-patterns-userprofile"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-userprofile"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "UserPool=\"us-east-1_LATPoV9Aq\" Service=\"userprofile\" Stage=\"prod\""
image_repositories = []
