version = 0.1
[default.deploy.parameters]
stack_name = "ws-serverless-patterns-polling"
resolve_s3 = true
s3_prefix = "ws-serverless-patterns-polling"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "OrdersTablename=\"ws-serverless-patterns-orders-OrdersTable-BVRNV8SURQAR\" UserPool=\"us-east-1_LATPoV9Aq\" Stage=\"dev\""
image_repositories = []
